---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: _PREFIX_tasks
  name: _PREFIX_tasks
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: _PREFIX_tasks
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: _PREFIX_tasks
    spec:
      containers:
      - image: _IMAGE_
        imagePullPolicy: IfNotPresent
        name: tasks
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: config-volume
          mountPath: /opt/jboss/configuration
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: _REGISTRY_SECRET_NAME_
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: _PREFIX_tasks-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: _PREFIX_tasks
  name: _PREFIX_tasks
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: _PREFIX_tasks
  sessionAffinity: None
  type: ClusterIP
