---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tasks
  name: tasks
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tasks
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tasks
    spec:
      containers:
      - image: _IMAGE_
        imagePullPolicy: IfNotPresent
        name: tasks
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: _REGISTRY_SECRET_NAME_
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tasks
  name: tasks
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tasks
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
